% the right frame
% callback are stored in files 'rf_*.m'
function GUI_right_frame(method,param1, param2)
    global conf
    global results
    global sim_sample_time
    
    persistent rp % right panel (parent for all right component)
    persistent obj_frame % keep a trace of the controls displayed to permit to hide them
    persistent rp_conf % store size of the right panel
    persistent vars_to_plot_panel
    persistent diagnoser_settings_panel
    global Prognoser
    
    
    switch method
        case 'init'
            f = param1;
            % draw the right panel
            rp_conf = struct('X', {conf.X_SIZE-conf.LEFT_MENU - 2*conf.MARGIN}, ...
                             'Y', {conf.Y_SIZE-conf.HEADER- 2*conf.MARGIN});
            rp = uipanel('Parent',f,'Title',' ', ...
                         'Units', 'pixels', ...
                         'BackgroundColor',conf.BG_COLOR, ...
                         'ForegroundColor',conf.FG_COLOR, ...
                         'Position',[
                            conf.LEFT_MENU + conf.MARGIN ...
                            conf.MARGIN ...
                            conf.X_SIZE-conf.LEFT_MENU - 2*conf.MARGIN, ...
                            conf.Y_SIZE-conf.HEADER- 2*conf.MARGIN ...
                          ]);
            vars_to_plot_panel = '';
            obj_frame = {};
            
            %welcome message
            obj_frame{1}=uicontrol('Parent', rp, 'Style','text',...
                'String', { 'Welcome in the Hybrid multimode System simulator software'}, ...
                'BackgroundColor',conf.BG_COLOR, ...
                'ForegroundColor',conf.FG_COLOR, ...
                'FontWeight', 'bold', ...
                'FontSize', 12, ...
                'Position',[...
                     conf.MARGIN, ...
                     rp_conf.Y - 5*conf.Y_BTN_SIZE, ...
                     rp_conf.X - 2*conf.MARGIN, ...
                     1*conf.Y_BTN_SIZE]);
                 
             obj_frame{2}=uicontrol('Parent', rp, 'Style','text',...
                'String', { 'To get started: create a new system or open an existing system.'}, ...
                'BackgroundColor',conf.BG_COLOR, ...
                'ForegroundColor',conf.FG_COLOR, ...
                'Position',[...
                     conf.MARGIN, ...
                     rp_conf.Y - 7*conf.Y_BTN_SIZE, ...
                     rp_conf.X - 2*conf.MARGIN, ...
                     1*conf.Y_BTN_SIZE]);
                 
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %% Creating a New system
        case 'frame_new'
            GUI_right_frame('clean');
            
            set(rp, 'Title', 'New system ...');
            
            % description
            obj_frame{1} = uicontrol('Parent', rp, 'Style','text',...
                'String', { 'Creation of a new hybrid system. Fill in these main parameters.' ...
                            'Number of input and output will be determined automatically when matrices A, B, C, D are given'}, ...
                'BackgroundColor',conf.BG_COLOR, ...
                'ForegroundColor',conf.FG_COLOR, ...
                'Position',[...
                     conf.MARGIN, ...
                     rp_conf.Y - 4*conf.MARGIN - 2*conf.Y_BTN_SIZE, ...
                     rp_conf.X - 2*conf.MARGIN, ...
                     2*conf.Y_BTN_SIZE]);

            % Field number of modes
            %  (label)
             obj_frame{2} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...
                'String', 'Number of modes in the multi-mode system: ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{3} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (conf.Y_BTN_SIZE + conf.MARGIN), ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
        
            % Field number of events
            %  (label)
             obj_frame{4} = uicontrol(...
                'Parent', rp, ...
                'Style','text',...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Number of events for the discrete system: ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 2*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{5} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...
                'Position',[ ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 2*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
            
            % Field Sample time
            %  (label)
             obj_frame{6} = uicontrol(...
                'Parent', rp, ...
                'Style','text',...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Sample time: ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 3*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{7} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 3*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
                 
            % Field for description
            %  (label)
             obj_frame{8} = uicontrol(...
                'Parent', rp, ...
                'Style','text',...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Description of the system: ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 4*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 4*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{9} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...
                'Position',[...
                     rp_conf.X - 4*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 4*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     3*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
            
            %% Below: Optionnal fields for automaticaly initialize all the
            %% matrixes
            % (label)
             obj_frame{17} = uicontrol(...
                'Parent', rp, ...
                'Style','text',...
                'BackgroundColor',conf.BG_COLOR, ...
                'ForegroundColor',conf.FG_COLOR, ...                
                'String', 'Fill in parameters below to automaticaly initialize every mode with right-sized matrix.', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 5*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.MARGIN, ...
                     conf.Y_BTN_SIZE] ...
                     );
                 
            %     Field for input size
            %  (label)
             obj_frame{11} = uicontrol(...
                'Parent', rp, ...
                'Style','text',...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Size of the continuous input    : ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 6*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{12} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 6*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
                 
            %     Field for output size
            %  (label)
             obj_frame{13} = uicontrol(...
                'Parent', rp, ...
                'Style','text',...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Size of the continuous output     ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 7*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{14} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 7*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
                 
            %     Field for order by default
            %  (label)
             obj_frame{15} = uicontrol(...
                'Parent', rp, ...
                'Style','text',...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Continuous state order    : ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 8*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{16} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - 8*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
                 
                 
             obj_frame{10} = uicontrol(...
                    'Parent', rp, 'Style','pushbutton','String','Create',...
                    'Position',[...
                         rp_conf.X - 2*conf.X_BTN_SIZE, ...
                         conf.MARGIN, ...
                         conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE], ...
                    'Callback',{@rf_Callback_create_new_system,obj_frame});
         % End creating new system

         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
         %% Editing a mode
         case 'edit_modes'


             % erase old frame
             GUI_right_frame('clean');
             
             if ~exist('param1', 'var')
                 param1 = 1;
             end

             % If this is not the 1st mode, then sizes must agree with
             % input and output size computed from the 1st mode
             if param1 > 1
                 buff_in=num2str(SysHybride('get_input_size'));
                 buff_out=num2str(SysHybride('get_output_size'));
                 required_size=struct('A',{...
%                                strcat(' Should be [', num2str(SysHybride('get_dyn_size',param1)), ...
%                                       'x', num2str(SysHybride('get_dyn_size',param1)),']:')...
                                ' Must be square.'
                                },'B',{...
                                strcat(' Should be [', num2str(SysHybride('get_dyn_size',param1)), ...
                                       'x', buff_in,']:')...
                                }, 'C', {...
                                strcat(' Should be [', buff_out, ...
                                       'x', num2str(SysHybride('get_dyn_size',param1)),']:')...
                                },'D', {
                                strcat(' Should be [', buff_out, ...
                                       'x', buff_in,']:')
                                },'x0', { ...
                                strcat('Initial state [1x', num2str(SysHybride('get_dyn_size',param1)),']:')...
                                });
             else
                 % no requirement for the 1st mode; it will set all
                 % parameters
                 required_size=struct('A',{''},'B',{''}, 'C', {''},'D', {''},'x0', {'Initial state: '});
             end

                                   
%              set(rp, 'Title', strcat('Editing mode n° ',num2str(param1),
%                  ' (', SysHybride('get_description', param1), ') '));
             set(rp, 'Title', 'Editing a mode');
             offset = 2;
            
             % description
             obj_frame{1} = uicontrol('Parent', rp, 'Style','text',...
                'String', {'Matrices must be typed in Matlab format [x1 y1 z1; x2 y2 z ...]; [rows x cols]'}, ...
                'BackgroundColor',conf.BG_COLOR, ...
                'ForegroundColor',conf.FG_COLOR, ...
                'Position',[...
                     conf.MARGIN, ...
                     rp_conf.Y - 4*conf.MARGIN - 2*conf.Y_BTN_SIZE, ...
                     rp_conf.X - 2*conf.MARGIN, ...
                     2*conf.Y_BTN_SIZE]);
                 
             % Select mode popup-menu (id=17)
             %  (label)
             obj_frame{16} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Mode to edit : ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset-1)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             % (popup-menu)
             buff = {};                 
             for i=1:SysHybride('get_automate_size')
                 buff{i}=strcat(SysHybride('get_description', i), ' (n°', num2str(i), ')');
             end
             obj_frame{17} = uicontrol(...
                    'Parent', rp, 'Style','popupmenu','String',buff, ...
                    'Value', param1, ...
                    'Position',[...
                         2*conf.X_BTN_SIZE + conf.MARGIN, ...
                         (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset-1)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                         2*conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE], ...
                     'Callback',{@btn_skiptomode_Callback});


                 
            % Field description
            %  (label)
             obj_frame{2} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Mode name (short description): ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+1)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{3} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String', SysHybride('get_description', param1), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+1)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     1.5*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
                 
            % Field for A-matrix
            %  (label)
             obj_frame{6} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', strcat('Dynamic matrix (A). ', required_size.A), ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+3)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{7} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String', mat2str(SysHybride('get_matA', param1)), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+3)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     1.5*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
                              
            % Field for B-matrix
            %  (label)
             obj_frame{8} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...
                'String', strcat('Input matrix (B). ',required_size.B), ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{9} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String', mat2str(SysHybride('get_matB', param1)), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     1.5*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
            % Field for C-matrix
            %  (label)
             obj_frame{10} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...
                'String', strcat('Observation matrix (C). ',required_size.C), ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+5)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{11} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String', mat2str(SysHybride('get_matC', param1)), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+5)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     1.5*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
                 
            % Field for D-matrix
            %  (label)
             obj_frame{12} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...
                'String', strcat('Direct transmission matrix (D). ',required_size.D), ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+6)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{13} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String', mat2str(SysHybride('get_matD', param1)), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+6)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     1.5*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
                 
             % Initial state
             %  (label)
             obj_frame{14} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...
                'String', required_size.x0, ...
                'Position', [...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+8)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{15} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String', mat2str(SysHybride('get_x0', param1)), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+8)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     1.5*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             % Next mode
             %  (label)
%              obj_frame{19} = uicontrol(...
%                 'Parent', rp, ...
%                 'Style','text', ...
%                 'BackgroundColor',conf.BG_COLOR_LABEL, ...
%                 'ForegroundColor',conf.FG_COLOR_LABEL, ...
%                 'String', 'Next modes ', ...
%                 'Position', [...
%                      conf.MARGIN, ...
%                      (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+10)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
%                      rp_conf.X - 2*conf.X_BTN_SIZE, ...
%                      conf.Y_BTN_SIZE] ...
%                      );
%              %  (input)
%              obj_frame{20} = uicontrol(...
%                 'Parent', rp, ...
%                 'Style','edit',...
%                 'String', mat2str(SysHybride('get_next_id', param1)), ...
%                 'BackgroundColor',conf.BG_COLOR_INPUT, ...
%                 'ForegroundColor',conf.FG_COLOR_INPUT, ...                
%                 'Position',[...
%                      rp_conf.X - 2*conf.X_BTN_SIZE, ...
%                      (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+10)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
%                      1.5*conf.X_BTN_SIZE, ...
%                      conf.Y_BTN_SIZE] ...
%                 );
             % Next mode : Button open popup
             %  (no label)
             obj_frame{21} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...
                'String', ['Next modes on events: ' mat2str(SysHybride('get_next_id', param1))], ...
                'Position', [...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+11)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (button)
             obj_frame{22} = uicontrol(...
                'Parent', rp, ...
                'Style','pushbutton',...
                'String', 'Edit', ...              
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+11)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     1.5*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE], ...
                'Callback', {@btn_edit_next_id_Callback, obj_frame, param1} ...
                );
                 
                 

             % Validation button
             obj_frame{18} = uicontrol(...
                    'Parent', rp, 'Style','pushbutton','String','Validate',...
                    'Position',[...
                         rp_conf.X - 2*conf.X_BTN_SIZE, ...
                         conf.MARGIN+conf.Y_BTN_SIZE, ...
                         conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE], ...
                    'Callback',{@rf_Callback_editmodesvalidate,obj_frame, param1});
         %end of edit mode frame
                
         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
         %% Editing an event
         case 'edit_events'
             
             % erase old frame
             GUI_right_frame('clean');
             
             if ~exist('param1', 'var')
                 param1 = 1;
             end

%              set(rp, 'Title', strcat('Editing event n° ',num2str(param1), ...
%                  ' (', SysHybride('get_event_name', param1), ') '));
             set(rp, 'Title', 'Editing an event');
            
             offset = 2;
            
             % description
             obj_frame{1} = uicontrol('Parent', rp, 'Style','text',...
                'String', {'Matrices must be typed in Matlab format [x1 y1 z1; x2 y2 z ...]; [rows x cols]'}, ...
                'BackgroundColor',conf.BG_COLOR, ...
                'ForegroundColor',conf.FG_COLOR, ...
                'Position',[...
                     conf.MARGIN, ...
                     rp_conf.Y - 4*conf.MARGIN - 2*conf.Y_BTN_SIZE, ...
                     rp_conf.X - 2*conf.MARGIN, ...
                     2*conf.Y_BTN_SIZE]);
                 
             % Select box (id=16)
            %  (label)
             obj_frame{16} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Event to edit: ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset-1)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             % (popupmenu)
             buff = {};                 
             for i=1:SysHybride('get_events_size')
                
                 buff{i}=strcat(SysHybride('get_event_name', i), ' (', num2str(i), ')');
             end
             obj_frame{17} = uicontrol(...
                    'Parent', rp, 'Style','popupmenu','String',buff, ...
                    'Value', param1, ...
                    'Position',[...
                         2*conf.X_BTN_SIZE+conf.MARGIN, ...
                         (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset-1)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                         2*conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE],...
                     'Callback',{@btn_skiptoevent_Callback}...  
                     );
                     
            % Field description
            %  (label)
             obj_frame{2} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Short description for this event    : ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+1)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{3} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String', SysHybride('get_event_name', param1), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+1)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %Checkbox observable/unobservable event  
             buff=SysHybride('get_event_obs', param1);
             if isempty(buff);
                 buff=0;
             end
             obj_frame{4} = uicontrol(...
                'Parent', rp, ...
                'Style','checkbox', ...
                'Value', buff, ...
                'String', 'This event is observable', ...
                'Position',[...
                     conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+3)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  Checkbox is a fault or not
             buff=SysHybride('get_event_fault', param1);
             if isempty(buff);
                 buff=0;
             end
             
             obj_frame{5} = uicontrol(...
                'Parent', rp, ...
                'Style','checkbox',...
                'Value', buff, ...
                'String', 'This event is a fault', ...            
                'Position',[...
                     conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     rp_conf.X- 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
                 
             %  Checkbox is a commandable event (for active diag)
             buff=SysHybride('get_event_commandable', param1);
             if isempty(buff);
                 buff=0;
             end
             
             obj_frame{8} = uicontrol(...
                'Parent', rp, ...
                'Style','checkbox',...
                'Value', buff, ...
                'String', 'This event is static', ...            
                'Position',[...
                     conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+5)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     rp_conf.X- 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
                 
                 
            % Field time schedule array
            %  (label)
             obj_frame{6} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Time schedule for this event (vector): ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+7)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{7} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String', mat2str(SysHybride('get_event_schedule', param1)), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+7)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );


                
%              % Skip button
%              obj_frame{17} = uicontrol(...
%                     'Parent', rp, 'Style','pushbutton','String','Skip to this event', ...
%                     'Position',[...
%                          2*conf.MARGIN+2*conf.X_BTN_SIZE, ...
%                          conf.MARGIN, ...
%                          1.2*conf.X_BTN_SIZE, ...
%                          conf.Y_BTN_SIZE], ...
%                     'Callback',{@btn_skiptoevent_Callback,obj_frame});
             


             % Validation button
             obj_frame{18} = uicontrol(...
                    'Parent', rp, 'Style','pushbutton','String','Validate',...
                    'Position',[...
                         rp_conf.X - 2*conf.X_BTN_SIZE, ...
                         conf.MARGIN+conf.Y_BTN_SIZE, ...
                         conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE], ...
                    'Callback',{@rf_Callback_editeventsvalidate,obj_frame, param1});    
             
         %end of edit event frame
                
         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
         %% Editing the automaton (relationship between events and next
         %% mode)
         case 'edit_automaton'
             % erase old frame
             GUI_right_frame('clean');
             
             if ~exist('param1', 'var')
                 param1 = 1;
             end

%              set(rp, 'Title', strcat('Editing event n° ',num2str(param1), ...
%                  ' (', SysHybride('get_event_name', param1), ') '));
             set(rp, 'Title', 'Editing an event');
            
             offset = 2;
            
             % description
             obj_frame{1} = uicontrol('Parent', rp, 'Style','text',...
                'String', {'Matrices must be typed in Matlab format [x1 y1 z1; x2 y2 z ...]; [rows x cols]'}, ...
                'BackgroundColor',conf.BG_COLOR, ...
                'ForegroundColor',conf.FG_COLOR, ...
                'Position',[...
                     conf.MARGIN, ...
                     rp_conf.Y - 4*conf.MARGIN - 2*conf.Y_BTN_SIZE, ...
                     rp_conf.X - 2*conf.MARGIN, ...
                     2*conf.Y_BTN_SIZE]);
                 
             % Select box (id=16)
            %  (label)
             obj_frame{16} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Event to edit: ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset-1)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             % (popupmenu)
             buff = {};                 
             for i=1:SysHybride('get_events_size')
                
                 buff{i}=strcat(SysHybride('get_event_name', i), ' (', num2str(i), ')');
             end
             obj_frame{17} = uicontrol(...
                    'Parent', rp, 'Style','popupmenu','String',buff, ...
                    'Value', param1, ...
                    'Position',[...
                         2*conf.X_BTN_SIZE+conf.MARGIN, ...
                         (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset-1)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                         2*conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE],...
                     'Callback',{@btn_skiptoevent_dyn_Callback}...  
                     );
                     
            % Field description
            %  (label)
             obj_frame{2} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Short description for this event    : ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+1)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %  (input)
             obj_frame{3} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String', SysHybride('get_event_name', param1), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+1)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
   
     obj_frame{22} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'MAX', ...
                'Position',[...
                     conf.X_BTN_SIZE*3, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );            
      obj_frame{23} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'OUTPUT', ...
                'Position',[...
                     conf.X_BTN_SIZE*2, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );           
         obj_frame{24} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Min', ...
                'Position',[...
                     conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );          
                 
                 
                 
                 
            N_Output = SysHybride('get_output_size');
          
            for i=1:N_Output 
               out = strcat('out',num2str(i));
               
            obj_frame{i+24} = uicontrol('Parent', rp, 'Style', 'text', ...
                 'String', out, ...
                 'Position',[...
                     conf.X_BTN_SIZE*2, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4+i)*(conf.Y_BTN_SIZE + conf.MARGIN) ,...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]);
                 
              
              obj_frame{2*(i+24)} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String',  SysHybride('get_born_sup',SysHybride('get_event_id', param1),i), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     conf.X_BTN_SIZE*3, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4+i)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );      
              obj_frame{2*(i+24)+1} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String', SysHybride('get_born_inf',SysHybride('get_event_id', param1),i), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4+i)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );   
            end
   
             % Validation button
             obj_frame{18} = uicontrol(...
                    'Parent', rp, 'Style','pushbutton','String','Validate',...
                    'Position',[...
                         rp_conf.X - 2*conf.X_BTN_SIZE, ...
                         conf.MARGIN+conf.Y_BTN_SIZE, ...
                         conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE], ...
                    'Callback',{@rf_Callback_editeventsdynamique,obj_frame, param1});    
             
             
         %end of edit automaton
         
         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
         %% Run the simulation         
         case 'run_simulation'
             % erase old frame
             GUI_right_frame('clean');
             %results.mark = -1;
             
             set(rp, 'Title', 'Running the simulation');
             offset = 1;
             
             %if we arrive here, SysHybride should be valid enough, so we
             %can initialize Diagnoser (only the 1st time (managed in Diagnoser))
             Diagnoser('init');
             PrognoserSet('update');

             %% Field simulation time
             % description
             obj_frame{2} = uicontrol('Parent', rp, 'Style','text',...
                'String', {'Simulation time (h)'}, ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]);
             %  (input)
             obj_frame{3} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String',num2str(SysHybride('get_total_time')) , ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             %% Field simulation step time
             % description
             obj_frame{22} = uicontrol('Parent', rp, 'Style','text',...
                'String', {'Simulation step time (h)'}, ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 3*conf.Y_BTN_SIZE) - (offset)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]);
             %  (input)
             obj_frame{23} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String',num2str(sim_sample_time) , ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 3*conf.Y_BTN_SIZE) - (offset)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
                 
             %% Lists box to select vars to plot (grouped into a panel)
             list_box_height = 1; % in number of Y_BTN_SIZE
%              vars_to_plot_panel = uipanel('Parent',rp,'Title',' ', ...
%                  'Units', 'pixels', ...
%                  'Title', 'Select inputs, outputs, events to plot (up to 4 plots)', ...
%                  'BackgroundColor',conf.BG_COLOR, ...
%                  'ForegroundColor',conf.FG_COLOR, ...
%                  'Position',[
%                     conf.MARGIN ...
%                     rp_conf.Y - (5*conf.Y_BTN_SIZE + (list_box_height+2)*conf.Y_BTN_SIZE) ...
%                     rp_conf.X - 3*conf.MARGIN, ...
%                     (2+list_box_height)*conf.Y_BTN_SIZE ...
%                   ]);
%               
%              % (label)
%              obj_frame{4} = uicontrol('Parent', vars_to_plot_panel, 'Style','text',...
%                 'String', {'Plot 1'}, ...
%                 'BackgroundColor',conf.BG_COLOR_LABEL, ...
%                 'ForegroundColor',conf.FG_COLOR_LABEL, ...
%                 'Position',[...
%                      conf.MARGIN+0*(conf.X_BTN_SIZE+conf.MARGIN), ...
%                      list_box_height*conf.Y_BTN_SIZE + conf.MARGIN, ...
%                      conf.X_BTN_SIZE, ...
%                      conf.Y_BTN_SIZE]);
%              % (listbox plot1)
%              obj_frame{5} = uicontrol('Parent', vars_to_plot_panel, 'Style', 'listbox', ...
%                  'String', {'test1','test2'}, ...
%                  'Position',[...
%                      conf.MARGIN+0*(conf.X_BTN_SIZE+conf.MARGIN), ...
%                      conf.MARGIN, ...
%                      conf.X_BTN_SIZE, ...
%                      list_box_height*conf.Y_BTN_SIZE]);
%                  
%              % (label)
%              obj_frame{6} = uicontrol('Parent', vars_to_plot_panel, 'Style','text',...
%                 'String', {'Plot 2'}, ...
%                 'BackgroundColor',conf.BG_COLOR_LABEL, ...
%                 'ForegroundColor',conf.FG_COLOR_LABEL, ...
%                 'Position',[...
%                      conf.MARGIN+1*(conf.X_BTN_SIZE+conf.MARGIN), ...
%                      list_box_height*conf.Y_BTN_SIZE + conf.MARGIN, ...
%                      conf.X_BTN_SIZE, ...
%                      conf.Y_BTN_SIZE]);
%              % (listbox plot2)
%              obj_frame{7} = uicontrol('Parent', vars_to_plot_panel, 'Style', 'listbox', ...
%                  'Position',[...
%                      conf.MARGIN+1*(conf.X_BTN_SIZE+conf.MARGIN), ...
%                      conf.MARGIN, ...
%                      conf.X_BTN_SIZE, ...
%                      list_box_height*conf.Y_BTN_SIZE]);
             
   
              
             %% Fields for the diagnoser
             diagnoser_settings_panel = uipanel('Parent',rp,'Title',' ', ...
                 'Units', 'pixels', ...
                 'Title', 'Simulation settings', ...
                 'BackgroundColor',conf.BG_COLOR, ...
                 'ForegroundColor',conf.FG_COLOR, ...
                 'Position',[
                    conf.MARGIN ...
                    rp_conf.Y - (5*conf.Y_BTN_SIZE + (list_box_height+2)*conf.Y_BTN_SIZE) - 6*conf.Y_BTN_SIZE - conf.MARGIN ...
                    rp_conf.X - 3*conf.MARGIN, ...
                    8*conf.Y_BTN_SIZE ...                    
                  ]);
%              Checkbox activate diagnoser
             obj_frame{20} = uicontrol(...
                'Parent', diagnoser_settings_panel, ...
                'Style','checkbox', ...
                'Value', Diagnoser('get_enable'), ...
                'String', 'Enable diagnoser', ...
                'Position',[...
                     conf.MARGIN+conf.X_BTN_SIZE, ...
                     6.6*conf.Y_BTN_SIZE - 1*conf.MARGIN, ...
                     rp_conf.X - 2*conf.X_BTN_SIZE-1*conf.MARGIN , ...
                     conf.Y_BTN_SIZE] ...
                     );
                 obj_frame{10} = uicontrol(...
                'Parent', diagnoser_settings_panel, ...
                'Style','checkbox', ...
                'Value', PrognoserSet('get_enable'), ...
                'String', 'Enable prognoser', ...
                'Position',[...
                     conf.MARGIN+conf.X_BTN_SIZE, ...
                     5.4*conf.Y_BTN_SIZE - 1*conf.MARGIN, ...
                     rp_conf.X - 2*conf.X_BTN_SIZE-1*conf.MARGIN , ...
                     conf.Y_BTN_SIZE] ...
                     ); 
             obj_frame{30} = uicontrol(...
                'Parent', diagnoser_settings_panel, ...
                'Style','checkbox', ...
                'Value', Diagnoser('get_spec_input'), ...
                'String', 'Specified continuous input', ...
                'Position',[...
                     conf.MARGIN+conf.X_BTN_SIZE, ...
                     4.2*conf.Y_BTN_SIZE - 1*conf.MARGIN, ...
                     rp_conf.X - 2*conf.X_BTN_SIZE-1*conf.MARGIN , ...
                     conf.Y_BTN_SIZE] ...
                     );   
             %%Field order ARR
             %(label)
             obj_frame{13} = uicontrol('Parent', diagnoser_settings_panel, 'Style','text',...
                'String', {'Orders of the parity space: '}, ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...
                'Position',[...
                     conf.MARGIN, ...
                     3*conf.Y_BTN_SIZE - 2*conf.MARGIN, ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]);
             %  (input) 
             obj_frame{14} = uicontrol(...
                'Parent', diagnoser_settings_panel, ...
                'Style','edit',...
                'String',mat2str(Diagnoser('get_ARR_order_optimal')) , ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     3*conf.Y_BTN_SIZE - 2*conf.MARGIN, ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
             % (button) auto set minimum
             obj_frame{19} = uicontrol(...
                    'Parent', diagnoser_settings_panel, 'Style','pushbutton','String','Auto',...
                    'Position',[...
                     rp_conf.X - 1*conf.X_BTN_SIZE+conf.MARGIN, ...
                     3*conf.Y_BTN_SIZE - 2*conf.MARGIN, ...
                     0.5*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE], ...
                    'Callback',{@btn_autosetARRorder_Callback, obj_frame});     
                 
              %%Field filter y threshold
              %(label)
             obj_frame{15} = uicontrol('Parent', diagnoser_settings_panel, 'Style','text',...
                'String', {'Residual precision '}, ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...
                'Position',[...
                     conf.MARGIN, ...
                     2*conf.Y_BTN_SIZE - 3*conf.MARGIN, ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]);
             %  (input)
             obj_frame{16} = uicontrol(...
                'Parent', diagnoser_settings_panel, ...
                'Style','edit',...
                'String',num2str(Diagnoser('get_filter_dy')) , ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     2*conf.Y_BTN_SIZE - 3*conf.MARGIN, ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
              %%Field filter time threshold
              %(label)
             obj_frame{17} = uicontrol('Parent', diagnoser_settings_panel, 'Style','text',...
                'String', {'Filter sensitivity (Number of time steps)'}, ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...
                'Position',[...
                     conf.MARGIN, ...
                     1*conf.Y_BTN_SIZE - 4*conf.MARGIN, ...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]);
             %  (input) /!\ May differ between each mode;
             obj_frame{18} = uicontrol(...
                'Parent', diagnoser_settings_panel, ...
                'Style','edit',...
                'String',num2str(Diagnoser('get_filter_dt')) , ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     rp_conf.X - 2*conf.X_BTN_SIZE, ...
                     1*conf.Y_BTN_SIZE - 4*conf.MARGIN, ...
                     conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );    
                 
             % Show hybrid system
             obj_frame{27} = uicontrol(...
                    'Parent', rp, 'Style','pushbutton','String','Show hybrid system',...
                    'Position',[...
                         rp_conf.X - 2*conf.X_BTN_SIZE, ...
                         conf.MARGIN+5*(conf.Y_BTN_SIZE+conf.MARGIN), ...
                         1.5*conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE], ...
                    'Callback',{@rf_Callback_show_hybridsystem, obj_frame});     
             % Show diagnosables groups
             obj_frame{24} = uicontrol(...
                    'Parent', rp, 'Style','pushbutton','String','Diagnosables groups',...
                    'Position',[...
                         rp_conf.X - 2*conf.X_BTN_SIZE, ...
                         conf.MARGIN+4*(conf.Y_BTN_SIZE+conf.MARGIN), ...
                         1.5*conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE], ...
                    'Callback',{@rf_Callback_showdiagnosablesgroups, obj_frame}); 
                
             % Show Automaton + Diagnoser Automaton
             obj_frame{25} = uicontrol(...
                    'Parent', rp, 'Style','pushbutton','String','Show automatons',...
                    'Position',[...
                         rp_conf.X - 2*conf.X_BTN_SIZE, ...
                         conf.MARGIN+3*(conf.Y_BTN_SIZE+conf.MARGIN), ...
                         1.5*conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE], ...
                    'Callback',{@rf_Callback_showautomatons, obj_frame});
                
             % launch simulation on click
             obj_frame{21} = uicontrol(...
                    'Parent', rp, 'Style','pushbutton','String','Run',...
                    'Position',[...
                         rp_conf.X - 2*conf.X_BTN_SIZE, ...
                         conf.MARGIN+2*(conf.Y_BTN_SIZE+conf.MARGIN), ...
                         1.5*conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE], ...
                    'FontWeight', 'bold', ...
                    'Callback',{@rf_Callback_runsimulation, obj_frame}); 

             % launch plot result figure on click
             obj_frame{26} = uicontrol(...
                    'Parent', rp, 'Style','pushbutton','String','Plot results',...
                    'Position',[...
                         rp_conf.X - 2*conf.X_BTN_SIZE, ...
                         conf.MARGIN+conf.Y_BTN_SIZE, ...
                         1.5*conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE], ...
                    'Callback',{@rf_Callback_plot_results, obj_frame});        
        %end of run simulation frame
                                     
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %% end of frames
        

  case 'edit_prognosis_parameters'
             % erase old frame
             GUI_right_frame('clean');
             if isempty(Prognoser) 
                  PrognoserSet('init');
             end
             if ~exist('param1', 'var')
                 param1 = 1;
             end
            if ~exist('param2', 'var')
                 param2 = 1;
            end
           
%              set(rp, 'Title', strcat('Editing event n° ',num2str(param1), ...
%                  ' (', SysHybride('get_event_name', param1), ') '));
             set(rp, 'Title', 'Edit fault weibull parameters');
            
             offset = 2;
            
             % description
             obj_frame{1} = uicontrol('Parent', rp, 'Style','text',...
                'String', {'Matrices must be typed in Matlab format [x1 y1 z1; x2 y2 z ...]; [rows x cols]'}, ...
                'BackgroundColor',conf.BG_COLOR, ...
                'ForegroundColor',conf.FG_COLOR, ...
                'Position',[...
                     conf.MARGIN, ...
                     rp_conf.Y - 4*conf.MARGIN - 2*conf.Y_BTN_SIZE, ...
                     rp_conf.X - 2*conf.MARGIN, ...
                     2*conf.Y_BTN_SIZE]);
                 
             % Select box (id=16)
            %  (label)
             obj_frame{16} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Fault event to edit: ', ...
                'Position',[...
                     conf.MARGIN, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset-1)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     2*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );
 % (popupmenu fault)
             buff = {};                 
             for i=1:SysHybride('get_events_size')
                if SysHybride('get_event_fault',i)
                 buff{i}=strcat(SysHybride('get_event_name', i), ' (', num2str(i), ')');
                end
             end
             obj_frame{17} = uicontrol(...
                    'Parent', rp, 'Style','popupmenu','String',buff, ...
                    'Value', param1, ...
                    'Position',[...
                         2*conf.X_BTN_SIZE+conf.MARGIN, ...
                         (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset-1)*(conf.Y_BTN_SIZE + conf.MARGIN), ...
                         2*conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE],...
                     'Callback',{@btn_skiptoprognose_fault_Callback}...  
                     );
            % Field description
        
            
 obj_frame{24} = uicontrol(...
                'Parent', rp, ...
                'Style','text', ...
                'BackgroundColor',conf.BG_COLOR_LABEL, ...
                'ForegroundColor',conf.FG_COLOR_LABEL, ...                
                'String', 'Parameters', ...
                'Position',[...
                     conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ...
                     );          
                 
                 
                 
            obj_frame{25} = uicontrol('Parent', rp, 'Style', 'text', ...
                 'String', 'Beta', ...
                 'Position',[...
                     conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+5)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]);
           
            obj_frame{26} = uicontrol('Parent', rp, 'Style', 'text', ...
                 'String', 'Eta', ...
                 'Position',[...
                     conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4+2)*(conf.Y_BTN_SIZE + conf.MARGIN) ,...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]);     
            
            obj_frame{27} = uicontrol('Parent', rp, 'Style', 'text', ...
                 'String', 'Gama', ...
                 'Position',[...
                     conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4+3)*(conf.Y_BTN_SIZE + conf.MARGIN) ,...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]);              
        
            obj_frame{28} = uicontrol('Parent', rp, 'Style', 'text', ...
                 'String', 'Pf0', ...
                 'Position',[...
                     conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4+4)*(conf.Y_BTN_SIZE + conf.MARGIN) ,...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]);   
            
           obj_frame{29} = uicontrol('Parent', rp, 'Style', 'text', ...
                 'String', 'Pfmax', ...
                 'Position',[...
                     conf.X_BTN_SIZE, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4+5)*(conf.Y_BTN_SIZE + conf.MARGIN) ,...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]);              
   if ~isempty(buff)
% (popupmenu mode)
             buff = {};                 
               for i=1:SysHybride('get_automate_size')
                 buff{i}=strcat(SysHybride('get_description', i), ' (n°', num2str(i), ')');
               end
             obj_frame{22} = uicontrol(...
                    'Parent', rp, 'Style','popupmenu','String',buff, ...
                    'Value', param2, ...
                    'Position',[...
                     conf.X_BTN_SIZE*2, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4)*(conf.Y_BTN_SIZE + conf.MARGIN) , ...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE] ,...
                     'Callback',{@btn_skiptoprognose_mode_Callback,get(obj_frame{17},'Value')}...  
                     );          
 
              
              obj_frame{30} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String',  PrognoserSet('get_Beta', param1,param2), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     conf.X_BTN_SIZE*2, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4+1)*(conf.Y_BTN_SIZE + conf.MARGIN) ,...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]...
                 );      
              obj_frame{31} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String',   PrognoserSet('get_Eta', param1,param2), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     conf.X_BTN_SIZE*2, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4+2)*(conf.Y_BTN_SIZE + conf.MARGIN) ,...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]...
                 );
             
             obj_frame{32} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String',   PrognoserSet('get_Gama', param1,param2), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     conf.X_BTN_SIZE*2, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4+3)*(conf.Y_BTN_SIZE + conf.MARGIN) ,...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]...
                 );
             obj_frame{33} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String',   PrognoserSet('get_Pf0', param1), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     conf.X_BTN_SIZE*2, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4+4)*(conf.Y_BTN_SIZE + conf.MARGIN) ,...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]...
                 );
             obj_frame{34} = uicontrol(...
                'Parent', rp, ...
                'Style','edit',...
                'String',   PrognoserSet('get_Pfmax', param1), ...
                'BackgroundColor',conf.BG_COLOR_INPUT, ...
                'ForegroundColor',conf.FG_COLOR_INPUT, ...                
                'Position',[...
                     conf.X_BTN_SIZE*2, ...
                     (rp_conf.Y - 2*conf.Y_BTN_SIZE) - (offset+4+5)*(conf.Y_BTN_SIZE + conf.MARGIN) ,...
                     0.9*conf.X_BTN_SIZE, ...
                     conf.Y_BTN_SIZE]...
                 );
   end
             % Validation button
             obj_frame{18} = uicontrol(...
                    'Parent', rp, 'Style','pushbutton','String','Validate',...
                    'Position',[...
                         rp_conf.X - 2*conf.X_BTN_SIZE, ...
                         conf.MARGIN+conf.Y_BTN_SIZE, ...
                         conf.X_BTN_SIZE, ...
                         conf.Y_BTN_SIZE], ...
                    'Callback',{@rf_Callback_editprog,obj_frame, param1,param2});    
             
             
         %end of edit automaton
        case 'clean'
            % remove all controls; we delete n-times the first.
            % this is more simple than starting deleting the n-th, then
            % n-1-th (filpud(1:length(obj_frame)))
            for i=1:length(obj_frame)
                try
                 delete(obj_frame{1});  % remove object from the figure
                 obj_frame(1)=[];       % remove from the stack
                catch 
                    %do noting
                end
            end
            
            %special case for the panels in 'run simulation'
            if ~isempty('vars_to_plot_panel') && ~ischar(vars_to_plot_panel)
                try
                    delete(vars_to_plot_panel);
                    clear vars_to_plot_panel;
                end
            end
            if ~isempty('diagnoser_settings_panel') && ~ischar(diagnoser_settings_panel)
                try
                    delete(diagnoser_settings_panel);
                    clear diagnoser_settings_panel;
                end
            end
            
            set(rp, 'Title', ' ');

            
        case 'quit'
            'quit right frame'
    end



        function btn_skiptomode_Callback(source, eventdata)
            get(source, 'Value')
            GUI_right_frame('edit_modes', get(source, 'Value'));
            
        function btn_skiptoevent_Callback(source, eventdata)
            GUI_right_frame('edit_events', get(source, 'Value'));
            
        function btn_skiptoevent_dyn_Callback(source, eventdata)
            GUI_right_frame('edit_automaton', get(source, 'Value'));
        
        function btn_skiptoprognose_mode_Callback(source,eventdata, param1)
            GUI_right_frame('edit_prognosis_parameters', param1,get(source, 'Value')); 
            
        function btn_skiptoprognose_fault_Callback(source,eventdata)
            GUI_right_frame('edit_prognosis_parameters',get(source, 'Value'),1);        
            
        function btn_edit_next_id_Callback(source, eventdata, obj_frame, mode_n)
            %we choose to validate first the form unless changes in the
            %fields below will be lost
            if rf_Callback_editmodesvalidate(source, eventdata, obj_frame, mode_n) == 0
                %next we can open the popup
                GUI_ask_next_id(mode_n);
            end
                

            
            

            

                
function btn_autosetARRorder_Callback(source, event, obj_frame)  
    set(obj_frame{14}, 'String', mat2str(Diagnoser('get_ARR_order_optimal')));
     Diagnoser('set_ARR_order', (Diagnoser('get_ARR_order_optimal')));
