function mw_Callback_logo(source, eventdata)

    helpdlg({'This software has been built by Manuel Klein' ...
        'for the research group DISCO of the LAAS-CNRS.' ...
        '' ...
        'August 2010' ...
        '' ...
        'http://www.laas.fr/'} ,'About')
end